name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of *Modmail Viewer* are you running?
      placeholder: "v0.6.0"
    validations:
      required: true
  - type: dropdown
    id: error-type
    attributes:
      label: In which part of the application does the error occur?
      options:
        - "Frontend"
        - "Backend"
        - "Unknown/both"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is.

        **To Reproduce**
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

        **Expected behavior**
        A clear and concise description of what you expected to happen.

        **Screenshots**
        If applicable, add screenshots to help explain your problem.

    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
   - type: checkboxes
    id: duplicate
    attributes:
      label: Code of Conduct
      description: I have checked to ensure this is not a duplicate issue.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
