contact_links:
  - name: Modmail Viewer Community support
    url: https://github.com/khakers/modmail-viewer/discussions
    about: Please ask and answer questions here.
  - name: Bug reports
    url: https://github.com/khakers/modmail-viewer/issues/new?template=bug_report.yml
    about: Report application bugs and issues here.
  - name: Feature Requests
    url: https://github.com/octo-org/octo-repo/issues/new?template=feature_request.md
    about: Request features here.
  - name: Security Issues
    url: https://github.com/khakers/modmail-viewer/security/advisories/new
    about: Please report potential security vulnerabilities here.
  